spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/project
spring.datasource.username = nonoy
spring.datasource.password = Admin_123


hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

com.project.api.props.jwt.secret = 2dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a
com.project.api.props.jwt.expiresIn = 86400000

com.project.api.props.cookie.name = authToken
com.project.api.props.cookie.expiresIn = 86400

spring.thymeleaf.cache=false

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

#logging.level.org.springframework.security=DEBUG
#logging.level.com.project.api.config.security=DEBUG